services:
  - type: web
    name: primeearn-offers-test
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: APP_TOKEN
        value: yQn0wD9FckeNshND
      - key: APP_HASH
        value: sltVRszfuB
      - key: NODE_VERSION
        value: 24
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false